### ISSUE TITLE
demo中title和toolbox、legend重叠的问题

### ISSUE THREAD

**Issue by Huang-Libo** [Pluto-Y/iOS-Echarts#17]
为什么上述三个控件会重叠在一起，可以解决这个问题吗？

**Comment by naihetxi** [comment]
可以通过调节属性，来确定它们各自的位置！发自网易邮箱大师
            在2016年08月31日 09:41，黄立波 写道:为什么上述三个控件会重叠在一起，可以解决这个问题吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pluto-Y/iOS-Echarts","title":"Pluto-Y/iOS-Echarts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Pluto-Y/iOS-Echarts"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"demo中title和toolbox、legend重叠的问题 (#17)"}],"action":{"name":"View Issue","url":"https://github.com/Pluto-Y/iOS-Echarts/issues/17"}}}

**Comment by naihetxi** [comment]
可以调节他们的坐标属性来解决！发自网易邮箱大师
            在2016年08月31日 09:41，黄立波 写道:为什么上述三个控件会重叠在一起，可以解决这个问题吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pluto-Y/iOS-Echarts","title":"Pluto-Y/iOS-Echarts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Pluto-Y/iOS-Echarts"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"demo中title和toolbox、legend重叠的问题 (#17)"}],"action":{"name":"View Issue","url":"https://github.com/Pluto-Y/iOS-Echarts/issues/17"}}}

**Comment by Pluto-Y** [comment]
@Huang-Libo 通过调整一些属性来调整各个控件位置，因为毕竟在现实使用中很少会三个都用的。Demo中是尽量重现Echart官网的内容。

**Comment by Huang-Libo** [comment]
@Pluto-Y 其实我也想问为什么Echart官网的demo中也会重叠，没有自适应的功能吗？

**Comment by SuperGuo751** [comment]
位置和是否显示,具体都是在echarts-all.js里面调试对吧?

**Comment by naihetxi** [comment]
不是在封装的对象里有专门的属性进行调节，不需要去js里调

**Comment by Pluto-Y** [comment]
@Huang-Libo 主要是里面的特别在iPhone里面，屏幕比较小，有些图显示起来控件就会不足，没办法做到自适应

**Comment by SuperGuo751** [comment]
那些个空间的位置只能有right left top bottom来控制么 也就是说只有八个位置咯 细调不可以对吧?

**Comment by Pluto-Y** [comment]
@SuperGuo751 可以用x和y来调整，用数值，比如x=@100这样

**Comment by SuperGuo751** [comment]
@Pluto-Y 可以可以 不错不错 谢谢版主

**Comment by Pluto-Y** [comment]
@SuperGuo751 不客气。
